### ISSUE TITLE
jquery 的引用BUG?

### ISSUE THREAD

**Issue by liyoc** [seajs/examples#12]
被这个问题彻底搞困惑了，接触seajs没几天， 一直被如何引入jquery 而困扰. 我怎么感觉jquery 必须放在 jquery/jquery/1.10.1/jquery.js  才能生效呢？

目录结构很简单， 所有文件都在一个目录中， index.html, application.js, jquery.js

index.html:

<script src="sea.js" ></script>

```
<script>

seajs.config({
    base: "./",
    alias: {
      "jquery": "jquery.js"   // 换成"jquery/jquery/1.10.1/jquery.js"， 并将jquery放入这个位置就没有问题。
    }
});
seajs.use("./application");

</script>
```

application.js:

define(function(require,exports,module){
     var $ = require('jquery');
     console.log($("#xxx").html());
 });

jquery.js  来自 seajs-master   example/sea-modules/jquery/jquery/1.10.1/jquery.js

错误是：  TypeError: $ is not a function， 
debug seajs.cache
jquery 其实已经被加载进来了。。。
但是发现还有一个  http://localhost:8080/plugins/seajs/mktry/jquery/jquery/1.10.1/jquery.js
这个就不知道从哪里来的了。。。

期待您的回复  :)

**Comment by youngwind** [comment]
谢谢！！被这个问题坑了大半个小时！！
