### ISSUE TITLE
require路径匹配不上的问题

### ISSUE THREAD

**Issue by YDSS** [seajs/examples#21]
**Hello**，刚开始学习seajs，使用require加载jquery时报**TypeError: $ is not a function**的错。在issue里找到了相关的一些解决办法，[#12](https://github.com/seajs/examples/issues/12),[#930](https://github.com/seajs/seajs/issues/930),[#438](https://github.com/seajs/seajs/issues/438),试过里面的解决方法但还是没有进展～～
   我使用的是spm下载下来的2.1.1版jquery库，模块id是**jquery/2.1.1/jquery**,

``` javascript
if ( typeof define === "function" && define.amd ) {
  define( "jquery/2.1.1/jquery", [], function() {
 return jQuery;  
  });
 }
```

seajs.config:

``` javascript
 seajs.config({
       base: './sea-modules/',
       alias: {
         'jquery': 'jquery/2.1.1/jquery.js'
       }
    });
```

因为是从spm下载的，jquery库放在sea-modules里面，按照在[#879](https://github.com/seajs/seajs/issues/879)里的方法，base路径+id名称，我应该是可以用require取到的～～
**另外**，还有一个不解之处，我发现在FF的net里有2个jquery资源的请求，一个获取到了资源（type=js），另一个没有取到（type=plain/html），没取到的也没有报404,请问这是什么机制呢？

**Comment by luobotang** [comment]
使用 Sea.js 直接加载第三方库貌似是个坑，要么改动第三方库的代码，要么自己做一些兼容处理。

对于暴露单个全局变量的库，例如 jQuery，我做了一个插件，在不修改库的情况下实现加载：
[seajs-var](https://www.npmjs.com/package/seajs-var)

感兴趣的同学可以看看源码，处理很简单。
